// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw1GeJ_04OR-qImxhiDoqQRNCg4iwRfqM',
    appId: '1:871049127447:web:3b6f8300b82751b7fe9e52',
    messagingSenderId: '871049127447',
    projectId: 'studyapp-eef7b',
    authDomain: 'studyapp-eef7b.firebaseapp.com',
    storageBucket: 'studyapp-eef7b.appspot.com',
    measurementId: 'G-EMXHTZJ3MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbpLAQpDsuh4uyTC4MAzUq76MXdAvM58g',
    appId: '1:871049127447:android:49c41bccc415b07ffe9e52',
    messagingSenderId: '871049127447',
    projectId: 'studyapp-eef7b',
    storageBucket: 'studyapp-eef7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuIM75yVFW0La-IKkBsT5TDzCstRq8V_w',
    appId: '1:871049127447:ios:7f23072172d80a88fe9e52',
    messagingSenderId: '871049127447',
    projectId: 'studyapp-eef7b',
    storageBucket: 'studyapp-eef7b.appspot.com',
    iosClientId: '871049127447-ebv04hj1tarnv75oohe6kggj3eg5qbh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuIM75yVFW0La-IKkBsT5TDzCstRq8V_w',
    appId: '1:871049127447:ios:7f23072172d80a88fe9e52',
    messagingSenderId: '871049127447',
    projectId: 'studyapp-eef7b',
    storageBucket: 'studyapp-eef7b.appspot.com',
    iosClientId: '871049127447-ebv04hj1tarnv75oohe6kggj3eg5qbh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyapp',
  );
}
